# Generated by Django 4.1 on 2022-09-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStage',
            fields=[
                ('exam_stage_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(choices=[(7, 'Раз в неделю'), (31, 'Раз в месяц')], default=7)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'ExamStage',
                'verbose_name_plural': 'ExamStages',
                'db_table': 'ExamStages',
            },
        ),
    ]
