# Generated by Django 4.1 on 2022-09-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation'),
        ('exams', '0002_exam_examplace_alter_examstage_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='reservation_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
