# Generated by Django 4.1 on 2022-09-05 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_reservation_id'),
        ('reservation', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='exam_place',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.examplace'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='exam_stage',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.examstage'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
