# Generated by Django 4.1 on 2022-09-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_is_used_reservation_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_confirmation',
            field=models.ImageField(blank=True, null=True, upload_to='payment_confirmation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_paid',
            field=models.CharField(choices=[('Не оплачено', 'Не оплачено'), ('Оплачено', 'Оплачено')], default='Не оплачено', max_length=25),
        ),
    ]
