# Generated by Django 4.1 on 2022-09-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_payment_confirmation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
    ]
